### ISSUE TITLE
Enhancement GetAdmin: Windows Control - GetAdmin as Windows Service

### ISSUE THREAD

**Issue by Robi1010MD** [Mic-M/ioBroker.windows-control#4]
Hi, I have installed the Windows Control Adapter and set up GetAdmin. When GetAdmin is started as a program, the commands work without problems. But if GetAdmin is running as a Windows service, a connection is available but no more commands are accepted. 

So far I also changed the service account GetAdmin was running on, unfortunately no change. 

Thanks for your help.

**Comment by Mic-M** [comment]
Hi, thanks for your issue.
So far, I have never tested GetAdmin using as a Windows service, but simply launched the GetAdmin.exe by double-clicking within the Windows OS Explorer and then choosing the option "Startup" to activate the "auto start" option.
I am not familiar with Windows services -- can you please explain why you need to run it as a "Windows service" versus launching normally.

**Comment by Mic-M** [comment]
No response provided - closed.
