### ISSUE TITLE
Update stable version in repo from 0.1.3 to 0.1.5

### ISSUE THREAD

**Issue by GermanBluefox** [Mic-M/ioBroker.windows-control#9]
# Think about update stable version to 0.1.5
**Version**: stable=**0.1.3** (120 days old) => latest=**0.1.5** (15 days old)
**Installs**: stable=**426** (73.96%), latest=**138** (23.96%), total=**576**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1723)

**Comment by Mic-M** [comment]
Completed several weeks ago.
